# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RhianaH
email: heppenstall.rhiana@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a personal portfolio website to store and remember all of my achievements
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rhiana.github.io" # the base hostname & protocol for your site
twitter_username: DevRhiana
github_username:  rhiana
youtube_username: UCPX-hg94gLZFnTTzVNfzFaw

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed
