# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rhiana
email: rhiana@heath.cc
description: > # this means to ignore newlines until "baseurl:"
  This site is about me! I will write a better description at then end
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rhiana.heath.cc/" # the base hostname & protocol for your site
twitter_username: RhianaHeath
github_username:  rhiana

# Build settings
markdown: kramdown
